IDEAS: dict[str, list[str]] = {
    # ── Engine category keys (looked up first) ───────────────────────────────
    "fuel_before": [
        "Oatmeal + banana + honey",
        "Whole grain pasta + chicken",
        "Brown rice + turkey + veggies",
        "Toast + 2 eggs + OJ",
        "Bagel + peanut butter + banana",
        "Pancakes + maple syrup + milk",
        "Greek yogurt + granola + berries",
        "Rice bowl + grilled chicken",
    ],
    "fuel_after": [
        "Chocolate milk",
        "Greek yogurt + mixed berries",
        "Turkey wrap + water",
        "Cottage cheese + pineapple",
        "Protein smoothie + banana",
        "Scrambled eggs + whole grain toast",
        "Tuna + whole grain crackers",
        "PB&J on whole wheat + milk",
    ],
    "everyday": [
        "Oatmeal + berries + milk",
        "Chicken + rice + veggies",
        "Eggs + toast + fruit",
        "Yogurt bowl + granola",
        "Turkey + cheese sandwich + apple",
        "Pasta + meat sauce + salad",
        "Grilled salmon + sweet potato",
        "PB&J + banana + milk",
    ],
    "quick_snack": [
        "Banana",
        "Toast + honey",
        "Granola bar",
        "Apple + peanut butter",
        "Rice cakes + jam",
        "Half bagel + cream cheese",
        "Orange slices",
        "Handful of pretzels + water",
    ],
    "between_games": [
        "Banana + sports drink",
        "Orange slices + chocolate milk",
        "Granola bar + water",
        "Turkey + crackers + electrolyte drink",
        "String cheese + fruit + juice",
        "PB crackers + banana",
        "Small PB&J + coconut water",
        "Trail mix + electrolyte drink",
    ],
    # ── category_key fallbacks ───────────────────────────────────────────────
    "carb": [
        "Banana + toast",
        "Rice bowl",
        "Bagel + honey",
        "Fruit smoothie",
        "Pretzels",
        "Pasta",
        "White rice",
        "English muffin + jam",
    ],
    "balanced": [
        "Oatmeal + berries",
        "Chicken + rice",
        "Eggs + toast",
        "Yogurt bowl",
        "Sandwich + fruit",
        "Turkey wrap",
        "Cottage cheese + fruit",
        "PB&J + banana",
    ],
    "recovery": [
        "Greek yogurt + fruit",
        "Chocolate milk",
        "Turkey wrap",
        "Smoothie + nut butter",
        "Eggs + whole grain toast",
        "Cottage cheese + pineapple",
        "Tuna + crackers",
    ],
    "hydrate": [
        "Water bottle (24 oz)",
        "Electrolyte drink",
        "Fruit + water",
        "Coconut water",
        "Watermelon slices",
    ],
}
